Add getopt package
hunter-packages/getopt pull request #1
Opened 2016-12-06 19:47 UTC by caseymcc

hunterize wingetopt and change name to getopt

2016-12-06 20:24 UTC, ruslo requested changes

2016-12-06 20:24 UTC, ruslo commented on CMakeLists.txt
> +add_library(getopt STATIC src/getopt.c src/getopt.h)
Why `STATIC`? Is it designed to not be used as shared? See:
* http://cgold.readthedocs.io/en/latest/tutorials/libraries/static-shared.html

2016-12-06 20:24 UTC, ruslo commented on Config.cmake.in
> +include("${CMAKE_CURRENT_LIST_DIR}/@targets_export_name@.cmake")
You should add `check_required_components`. In this case if user wrongly call `find_package(getopt REQUIRED nonexistent_component)` the error will be reported. See https://github.com/forexample/package-example/blob/cf2ea1d6a209fb9eca2ab83fdd0ac15fe4d3e807/Foo/cmake/Config.cmake.in

2016-12-06 22:00 UTC, caseymcc commented on CMakeLists.txt
> +add_library(getopt STATIC src/getopt.c src/getopt.h)
It is not setup for dynamic builds, would need some _dllexports for that. Could be added but considering it is only 2 functions likely not worth it.

2016-12-06 22:05 UTC, caseymcc commented on Config.cmake.in
> +include("${CMAKE_CURRENT_LIST_DIR}/@targets_export_name@.cmake")
Ill defer to you on the cmake config stuff, haven't really worked with it before using hunter.

2016-12-06 22:09 UTC, caseymcc commented
Added check_required_components to config file. Unless you see something else should be good to go.

2016-12-07 03:12 UTC, ruslo requested changes

2016-12-07 03:12 UTC, ruslo commented on Config.cmake.in
> +include("${CMAKE_CURRENT_LIST_DIR}/@targets_export_name@.cmake")
As far as I understand `check_required_components` will not work without `@PACKAGE_INIT@`. Just copy/paste the `Config.cmake.in` from the link I provided.

2019-08-25 13:45 UTC, ruslo commented
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst

2019-08-25 13:45 UTC, closed without merging